[package]
name = "pylon-db-derive"
description = "#[derive(Queryable)] for the Pylon Rust client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["pylon", "postgres", "postgresql", "database", "derive"]
categories = ["database", "development-tools::procedural-macro-helpers"]

[lib]
name = "pylon_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
