from __future__ import annotations

import enum

from . import _collector


class On(enum.IntFlag):
    """Mutation events that fire a trigger or rewrite.

    Flags can be combined with ``|``::

        On.Insert | On.Update
    """

    Insert = 1
    Update = 2
    Delete = 4


class Timing(enum.Enum):
    """When a trigger fires relative to the mutation event."""

    Before = "Before"
    After = "After"
    InsteadOf = "InsteadOf"


class Trigger:
    """PostgreSQL trigger declared as a class-body expression.

    Usage::

        Trigger(
            on=On.Insert | On.Update,
            timing=Timing.After,
            handler='.some.pyql.expression',
        )

    Names are auto-generated by hashing at DDL-generation time.
    """

    def __init__(self, *, on: On, timing: Timing, handler: str) -> None:
        self.on = on
        self.timing = timing
        self.handler = handler
        _collector.register(self)

    def __repr__(self) -> str:
        return f"Trigger(on={self.on!r}, timing={self.timing!r}, handler={self.handler!r})"


class Rewrite:
    """Mutation rewrite declared inside ``Property[T, ...]`` or ``Link[T, ...]``.

    Rewrites transform a PyQL mutation at execution time before it reaches the
    database. ``On.Insert`` and ``On.Update`` support at most one rewrite per
    property; ``On.Delete`` rewrites are declared by convention on a property.

    Usage::

        name: Property[str,
            Rewrite(On.Insert, '.name ++ " (created)"'),
            Rewrite(On.Update, '.name ++ " (updated)"'),
        ]
    """

    def __init__(self, on: On, handler: str) -> None:
        self.on = on
        self.handler = handler

    def __repr__(self) -> str:
        return f"Rewrite({self.on!r}, {self.handler!r})"
