#
# This source file is part of the Pylon open source project.
#
# Copyright (c) 2026 Jaldis B.V.
#
# Licensed under the MIT OR Apache-2.0 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://opensource.org/licenses/MIT
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Generates `pylon/namespaces.pyi` from the stdlib registry.

The `std`/`math`/`cal`/`sys` objects resolve attributes at runtime through
`__getattr__`, which no type checker can see through — so without a stub the
editor offers no completion and no arity checking for the very surface this
package exists to expose. Rather than hand-maintain ~150 signatures, they're
generated from the same registry the runtime validates against, which keeps
the two from drifting.

The result is checked in (editors don't run generators) and
`tests/test_stdlib_namespace.py` fails if it goes stale.

Regenerate with::

    python -m pylon._stubgen
"""

from __future__ import annotations

import keyword
import subprocess
import sys
from pathlib import Path

from pylon import stdlib
from pylon.modelquery import _INFIX_ALIASES

#: Namespace object name -> the PyQL namespace it wraps.
_NAMESPACES = (('std', 'std'), ('math', 'math'), ('cal', 'cal'), ('sys', 'sys'))

_HEADER = """#
# This source file is part of the Pylon open source project.
#
# Copyright (c) 2026 Jaldis B.V.
#
# Licensed under the MIT OR Apache-2.0 license (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://opensource.org/licenses/MIT
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# @generated by `python -m pylon._stubgen` from the PyQL stdlib registry.
# Do not edit by hand — regenerate instead.
#
# Argument types are deliberately permissive: every parameter accepts either a
# Python value (which becomes a query parameter) or a field path / nested call
# from the expression tree, so a precise annotation would reject valid code.
# What the stub buys is *name completion and arity*, which is what a runtime
# `__getattr__` namespace can never give an editor on its own.

from typing import Any, overload

from pylon.modelquery import _ConstantCall, _Node

_Arg = Any
_Constant = _ConstantCall

"""


def _param_name(raw: str, index: int) -> str:
    """A safe Python identifier for a registry parameter name."""
    name = raw or f'arg{index}'
    if keyword.iskeyword(name) or keyword.issoftkeyword(name):
        name = f'{name}_'
    return name


def _signature(entry: dict, method_name: str) -> str:
    """One `def name(self, ...) -> _Node: ...` line.

    Every parameter is positional-only (`/`): PyQL calls are positional, and
    it frees the stub from having to promise that registry parameter names
    are stable keyword names. The exception is a named-only parameter, which
    is keyword-only and defaulted, exactly as PyQL takes it.
    """
    params = stdlib.positional_params(entry)
    named = stdlib.named_params(entry)
    variadic_at = next((i for i, p in enumerate(params) if p['variadic']), None)

    # A variadic that isn't last (`std::json_set(j, path..., val)`) has no
    # Python spelling — `*args` must be the final positional group. Fall back
    # to a fully open signature so the name still completes and the call still
    # type-checks; the runtime arity check in `stdlib.check_call` remains the
    # real gate either way.
    if variadic_at is not None and variadic_at != len(params) - 1:
        return f'    def {method_name}(self, *args: _Arg) -> _Node: ...'

    parts: list[str] = ['self']
    for i, p in enumerate(params):
        pname = _param_name(p['name'], i)
        parts.append(f'*{pname}: _Arg' if p['variadic'] else f'{pname}: _Arg')

    # `/` marks the end of positional-only params. Legal only when at least
    # one such parameter precedes it, and never after `*args`.
    if params and variadic_at is None:
        parts.append('/')
    if named:
        if variadic_at is None:
            parts.append('*')
        parts.extend(f'{p["keyword"]}: _Arg = ...' for p in named)
    return f'    def {method_name}({", ".join(parts)}) -> _Node: ...'


def _distinct_signatures(entries: list[dict]) -> list[dict]:
    """Overloads deduplicated by shape, since several registry entries often
    differ only in argument *type* — which this stub doesn't express, so they
    would otherwise emit as identical duplicate lines."""
    seen: set[tuple] = set()
    out: list[dict] = []
    for e in entries:
        shape = (
            len(stdlib.positional_params(e)),
            tuple(p['variadic'] for p in e['params']),
            tuple(p['keyword'] for p in stdlib.named_params(e)),
        )
        if shape in seen:
            continue
        seen.add(shape)
        out.append(e)
    return out


def _class_for(namespace: str) -> str:
    lines = [f'class _{namespace.capitalize()}Namespace:']

    body: list[str] = []
    for name in sorted(stdlib.names(namespace)):
        entries = stdlib.overloads(namespace, name)
        # `std::assert` is reachable as `std.assert_` — `assert` is a Python
        # keyword and can't be a method name here or at the call site.
        attr = stdlib.python_name(name)

        if stdlib.is_constant(namespace, name):
            # A value that is also callable, so both `math.pi` and `math.pi()`
            # type-check — see `modelquery._ConstantCall`.
            body.append(f'    {attr}: _Constant')
            continue

        shapes = _distinct_signatures(entries)
        if len(shapes) == 1:
            body.append(_signature(shapes[0], attr))
        else:
            for e in sorted(shapes, key=lambda e: (len(stdlib.positional_params(e)), len(stdlib.named_params(e)))):
                body.append('    @overload')
                body.append(_signature(e, attr))

    if namespace == 'std':
        # Grammar-keyword pseudo-functions. These have no registry entry (see
        # `_INFIX_ALIASES`), so they'd be invisible to completion otherwise.
        for alias in sorted(_INFIX_ALIASES):
            body.append(f'    def {alias}(self, left: _Arg, right: _Arg, /) -> _Node: ...')

    if not body:
        body.append('    ...')
    lines.extend(body)
    return '\n'.join(lines)


def _ruff_format(text: str) -> str:
    """Run the generated text through `ruff format`.

    A few signatures are long enough to exceed the project's line limit, and
    hand-wrapping them to match ruff byte-for-byte is guesswork. Formatting
    here instead keeps the checked-in stub lint-clean without a per-file
    carve-out, and keeps `generate()` the single definition of the expected
    content so the staleness test stays honest.

    Falls back to the unformatted text when ruff isn't on PATH — it's a dev
    dependency, and an unformatted stub is still a correct one.
    """
    try:
        proc = subprocess.run(
            [sys.executable, '-m', 'ruff', 'format', '--stdin-filename', 'namespaces.pyi', '-'],
            input=text,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return text
    return proc.stdout


def generate() -> str:
    """The full text of `pylon/namespaces.pyi`."""
    blocks = [_HEADER.lstrip('\n')]
    for obj_name, namespace in _NAMESPACES:
        blocks.append(_class_for(namespace))
        blocks.append('')
        blocks.append(f'{obj_name}: _{namespace.capitalize()}Namespace')
        blocks.append('')
    return _ruff_format('\n'.join(blocks).rstrip('\n') + '\n')


def stub_path() -> Path:
    return Path(__file__).parent / 'namespaces.pyi'


def main() -> None:
    path = stub_path()
    path.write_text(generate())
    print(f'wrote {path}')


if __name__ == '__main__':
    main()
